version: '3.1'

services:
  php-apache:
    image: php:8.1-apache
    ports:
      - '80:80'
    volumes:
      - ./src:/var/www/html

  db:
    build: database
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1

volumes:
  db: